name: Generate Audio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-audio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate audio
      env:
        ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
      run: |
        cat <<EOF > generate_audio_https.py
        import os
        import requests

        # Load API key
        ELEVEN_LABS_API_KEY = os.getenv("ELEVEN_LABS_API_KEY")
        if not ELEVEN_LABS_API_KEY:
            print("Error: ELEVEN_LABS_API_KEY is not set.")
            exit(1)

        print(f"ELEVEN_LABS_API_KEY (partial): {ELEVEN_LABS_API_KEY[:5]}...")

        # Set API URL and headers
        VOICE_ID = "Mv8AjrYZCBkdsmDHNwcB".strip()
        API_URL = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
        headers = {
            "xi-api-key": ELEVEN_LABS_API_KEY.strip(),
            "Content-Type": "application/json",
        }

        payload = {"text": "こんにちは、元気ですか？"}
        print("Payload:", payload)
        print("Headers:", headers)

        # Make the request
        response = requests.post(API_URL, json=payload, headers=headers)
        print("Response Code:", response.status_code)
        print("Response Headers:", response.headers)

        # Save response content for debugging
        debug_path = "response_debug.txt"
        with open(debug_path, "w") as debug_file:
            debug_file.write(response.text)

        # Save the file if successful
        if response.status_code == 200:
            WORKSPACE = os.getenv("GITHUB_WORKSPACE", ".")
            OUTPUT_DIR = os.path.join(WORKSPACE, "processed-audio")
            os.makedirs(OUTPUT_DIR, exist_ok=True)
            output_path = os.path.join(OUTPUT_DIR, "test.mp3")
            with open(output_path, "wb") as audio_file:
                audio_file.write(response.content)
            print(f"Audio saved to {output_path}")
        else:
            print("Error:", response.text)
        EOF

        python generate_audio_https.py

    - name: List generated files
      run: ls -l processed-audio || echo "No files generated"

    - name: Upload audio artifact
      uses: actions/upload-artifact@v3
      with:
        name: generated-audio
        path: processed-audio/test.mp3
