name: Generate and Debug Audio

on:
  workflow_dispatch:

jobs:
  generate-audio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate audio with debugging
      env:
        ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
      run: |
        echo "Setting up API call..."
        mkdir -p processed-audio

        python - <<EOF
        import os
        import requests

        # Load API key and validate
        ELEVEN_LABS_API_KEY = os.getenv("ELEVEN_LABS_API_KEY")
        if not ELEVEN_LABS_API_KEY:
            print("Error: ELEVEN_LABS_API_KEY is not set.")
            exit(1)

        # Set API URL and headers
        VOICE_ID = "Mv8AjrYZCBkdsmDHNwcB"
        API_URL = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
        headers = {
            "xi-api-key": ELEVEN_LABS_API_KEY,
            "Content-Type": "application/json",
        }
        payload = {"text": "こんにちは、元気ですか？"}

        # Log headers and payload
        print("Headers:", headers)
        print("Payload:", payload)

        # Make API call
        response = requests.post(API_URL, json=payload, headers=headers)

        # Log response details
        print("Response Code:", response.status_code)
        print("Response Headers:", response.headers)
        print("Response Body:", response.text)

        # Save audio file if successful
        if response.status_code == 200:
            output_path = "processed-audio/test.mp3"
            with open(output_path, "wb") as f:
                f.write(response.content)
            print(f"Audio file saved at {output_path}")
        else:
            print(f"Failed to generate audio. Error: {response.status_code}, {response.text}")
            exit(1)
        EOF

    - name: List processed files
      run: |
        echo "Listing files in processed-audio directory:"
        ls -l processed-audio || echo "No files found in processed-audio directory."
