name: Generate Translation Audio

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push: # Automatically triggers on new file uploads
    paths:
      - processed/*.txt # Trigger when new processed files are added to the 'processed' directory

jobs:
  generate-audio:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Extract Translation and Generate Audio
      - name: Generate Audio from Translation
        env:
          ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
        run: |
          import os
          import re
          import requests

          ELEVEN_LABS_API_KEY = os.getenv("ELEVEN_LABS_API_KEY")
          API_URL = "https://api.elevenlabs.io/v1/text-to-speech"
          VOICE_ID = "Mv8AjrYZCBkdsmDHNwcB"  # Voice ID provided

          def extract_translation(filepath):
              with open(filepath, 'r', encoding='utf-8') as file:
                  content = file.read()
              match = re.search(r"\\*\\*Translation\\*\\*:\\n(.*?)\\n\\n", content, re.DOTALL)
              if match:
                  return match.group(1).strip().split("\\n")
              return []

          def generate_audio(text, output_path):
              headers = {
                  "Authorization": f"Bearer {ELEVEN_LABS_API_KEY}",
                  "Content-Type": "application/json",
              }
              payload = {
                  "text": text,
                  "voice_id": VOICE_ID
              }
              response = requests.post(API_URL, json=payload, headers=headers)
              if response.status_code == 200:
                  with open(output_path, "wb") as audio_file:
                      audio_file.write(response.content)
                  print(f"Audio saved to {output_path}")
              else:
                  print(f"Failed to generate audio: {response.text}")

          processed_dir = "processed"
          output_dir = "processed-audio"
          os.makedirs(output_dir, exist_ok=True)

          for filename in os.listdir(processed_dir):
              if filename.endswith(".txt"):
                  filepath = os.path.join(processed_dir, filename)
                  translations = extract_translation(filepath)
                  if translations:
                      for idx, line in enumerate(translations, start=1):
                          audio_output_path = os.path.join(output_dir, f"{filename}-{idx}.mp3")
                          generate_audio(line, audio_output_path)
