name: Generate Audio

on:
  workflow_dispatch:

jobs:
  generate-audio:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (if needed for debugging purposes)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Debug Environment Variables
      - name: Debug Secrets and Variables
        run: |
          echo "Debugging Secrets and Variables..."
          if [[ -z "${{ secrets.ELEVEN_LABS_API_KEY }}" ]]; then
            echo "ELEVEN_LABS_API_KEY is not set!"
            exit 1
          else
            echo "ELEVEN_LABS_API_KEY is set."
          fi
          echo "Using VOICE_ID: Mv8AjrYZCBkdsmDHNwcB"

      # Step 4: Send API Request Using cURL
      - name: Generate Audio
        env:
          ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
        run: |
          # Set Variables
          API_URL="https://api.elevenlabs.io/v1/text-to-speech/Mv8AjrYZCBkdsmDHNwcB"
          OUTPUT_FILE="processed-audio/test.mp3"
          PAYLOAD='{"text": "こんにちは、元気ですか？"}'

          # Debugging: Log Variables
          echo "API URL: $API_URL"
          echo "Payload: $PAYLOAD"

          # Create output directory
          mkdir -p processed-audio

          # Make the API Request
          echo "Sending request to Eleven Labs API..."
          curl -X POST "$API_URL" \
            -H "xi-api-key: $ELEVEN_LABS_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            --output "$OUTPUT_FILE" \
            --silent --show-error --fail

          # Verify Output
          if [[ -f "$OUTPUT_FILE" ]]; then
            echo "Audio successfully saved to $OUTPUT_FILE"
          else
            echo "Failed to generate audio. Please check the API response."
            exit 1
          fi

      # Step 5: Optional Debugging - Log Output File (if generated)
      - name: Log Output File
        if: success()
        run: |
          echo "Output file contents (hex):"
          xxd processed-audio/test.mp3 || echo "Output file not found."
