name: Generate Translation Audio

on:
  workflow_dispatch: # Allows manual triggering of the workflow with input
    inputs:
      date:
        description: "Date to process (e.g., 2025-01-10)"
        required: true
        default: ""

  push: # Automatically triggers when daily summaries are processed
    paths:
      - processed/*.txt # Monitor the 'processed' directory for new files

jobs:
  generate-audio:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run Python script
      - name: Generate Audio from Translation
        env:
          ELEVEN_LABS_API_KEY: ${{ secrets.ELEVEN_LABS_API_KEY }}
        run: python generate_audio.py ${{ github.event.inputs.date }}
