name: Monthly Summary Compilation

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year for the summary (YYYY)'
        required: false
        default: ''
      month:
        description: 'Month for the summary (MM)'
        required: false
        default: ''
  schedule:
    - cron: "0 2 1 * *" # Runs monthly on the 1st at 2:00 AM UTC

jobs:
  compile-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Year and Month
        id: determine_date
        run: |
          YEAR=${{ github.event.inputs.year }}
          MONTH=${{ github.event.inputs.month }}

          if [ -z "$YEAR" ] || [ -z "$MONTH" ]; then
            LAST_MONTH_DATE=$(date -d "last month" "+%Y-%m")
            YEAR=${YEAR:-${LAST_MONTH_DATE%-*}}
            MONTH=${MONTH:-${LAST_MONTH_DATE#*-}}
          fi

          echo "YEAR=$YEAR" >> $GITHUB_ENV
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "Determined year and month: $YEAR-$MONTH"

      - name: Set Output File Path
        run: |
          mkdir -p monthly-summaries
          OUTPUT_FILE="monthly-summaries/${YEAR}-${MONTH}-summary.txt"
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      - name: Gather Vocabulary and Summaries
        id: gather_data
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PROCESSED_FILES=$(find processed/ -type f -name "${YEAR}-${MONTH}-*.txt")

          if [ -z "$PROCESSED_FILES" ]; then
            echo "Error: No processed files found for ${YEAR}-${MONTH}."
            exit 1
          fi

          # Aggregate all text for OpenAI API analysis
          ALL_TEXT=""
          for FILE in $PROCESSED_FILES; do
            ALL_TEXT="$ALL_TEXT\n\n$(cat "$FILE")"
          done

          # Use OpenAI API for vocabulary analysis
          PAYLOAD=$(jq -n --arg text "$ALL_TEXT" '{
            model: "gpt-3.5-turbo",
            messages: [
              {
                role: "user",
                content: (
                  "Analyze the following text and extract a vocabulary frequency analysis. For each word, include:\n" +
                  "- The word in its original script\n" +
                  "- The romaji (phonetic transcription)\n" +
                  "- A brief definition\n\n" +
                  "Format as:\n\n" +
                  "Word | Romaji | Definition | Frequency\n\n" +
                  "Text to analyze:\n" +
                  $text
                )
              }
            ],
            max_tokens: 2000
          }')

          RESPONSE=$(echo "$PAYLOAD" | curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @-)

          VOCABULARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: Unable to process vocabulary."')

          if [[ "$VOCABULARY" == Error* ]]; then
            echo "Error during vocabulary analysis: $VOCABULARY"
            exit 1
          fi

          # Write vocabulary and summaries to the output file
          echo -e "Vocabulary Analysis:\n$VOCABULARY\n\nSummaries:\n" > "$OUTPUT_FILE"
          for FILE in $PROCESSED_FILES; do
            echo -e "\n### ${FILE} ###\n" >> "$OUTPUT_FILE"
            cat "$FILE" >> "$OUTPUT_FILE"

      - name: Upload Monthly Summary
        uses: actions/upload-artifact@v4
        with:
          name: Monthly-Summary-${{ env.YEAR }}-${{ env.MONTH }}
          path: ${{ env.OUTPUT_FILE }}
