name: Monthly Scenario Creation

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year for the scenario (YYYY)'
        required: false
        default: ''
      month:
        description: 'Month for the scenario (MM)'
        required: false
        default: ''
  schedule:
    - cron: "0 3 1 * *" # Runs monthly on the 1st at 3:00 AM UTC

jobs:
  create-scenario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tiktoken

      - name: Determine Year and Month
        id: determine_date
        run: |
          YEAR=${{ github.event.inputs.year }}
          MONTH=${{ github.event.inputs.month }}

          if [ -z "$YEAR" ] || [ -z "$MONTH" ]; then
            LAST_MONTH_DATE=$(date -d "last month" "+%Y-%m")
            YEAR=${YEAR:-${LAST_MONTH_DATE%-*}}
            MONTH=${MONTH:-${LAST_MONTH_DATE#*-}}
          fi

          echo "YEAR=$YEAR" >> $GITHUB_ENV
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "Determined year and month: $YEAR-$MONTH"

      - name: Set Input and Output Paths
        run: |
          INPUT_FILE="monthly-summaries/${{ env.YEAR }}-${{ env.MONTH }}-summary.txt"
          OUTPUT_FILE="monthly-scenario/${{ env.YEAR }}-${{ env.MONTH }}-scenario.txt"
          echo "INPUT_FILE=$INPUT_FILE" >> $GITHUB_ENV
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      - name: Check for Monthly Summary
        run: |
          if [ ! -f "$INPUT_FILE" ]; then
            echo "Error: Monthly summary file $INPUT_FILE does not exist."
            exit 1
          fi

      - name: Generate Scenario Using OpenAI API with Streaming and Exact Token Count
        id: generate_scenario
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          SUMMARY=$(cat "$INPUT_FILE")

          # Python script to get exact token count and truncate if needed
          python - <<EOF
          import tiktoken

          # Load GPT-4 tokenizer
          enc = tiktoken.encoding_for_model("gpt-4")

          # Constants
          SYSTEM_MESSAGE_TOKENS = 60  # Shortened system message
          MAX_COMPLETION_TOKENS = 1000
          MAX_TOTAL_TOKENS = 8192
          MAX_INPUT_TOKENS = MAX_TOTAL_TOKENS - SYSTEM_MESSAGE_TOKENS - MAX_COMPLETION_TOKENS

          # Read input
          with open("$INPUT_FILE", "r", encoding="utf-8") as f:
              summary = f.read()

          # Get token count
          tokens = enc.encode(summary)
          token_count = len(tokens)

          print(f"Exact Token Count: {token_count}")
          print(f"Maximum Allowed Input Tokens: {MAX_INPUT_TOKENS}")

          # If too long, truncate input
          if token_count > MAX_INPUT_TOKENS:
              print("Input exceeds token limit. Truncating...")
              tokens = tokens[:MAX_INPUT_TOKENS]  # Hard limit tokens
              summary = enc.decode(tokens)
              print(f"Input truncated to {len(tokens)} tokens.")

          # Save processed summary
          with open("processed_summary.txt", "w", encoding="utf-8") as f:
              f.write(summary)
          EOF

          # Read back truncated summary
          SUMMARY=$(cat processed_summary.txt)

          # Create API payload with streaming enabled
          PAYLOAD=$(jq -n --arg summary "$SUMMARY" '{
            model: "gpt-4",
            stream: true,
            messages: [
              {
                role: "system",
                content: "Generate a realistic dialogue scenario. Output: 1. Japanese script, 2. Romaji, 3. English translation. Keep under 1000 tokens."
              },
              {
                role: "user",
                content: $summary
              }
            ],
            max_tokens: 1000
          }')

          echo "Sending request to OpenAI API with streaming enabled..."

          # Process streamed response and save to file
          RESPONSE=$(echo "$PAYLOAD" | curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @- | tee "$OUTPUT_FILE")

          # Check if the response contains an error
          if grep -q '"error"' <<< "$RESPONSE"; then
            echo "Error during scenario generation: $(jq -r '.error.message' <<< "$RESPONSE")"
            exit 1
          fi

      - name: Commit and Push Scenario to Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          mkdir -p $(dirname "$OUTPUT_FILE")
          git add "$OUTPUT_FILE"
          git commit -m "Add monthly scenario for ${{ env.YEAR }}-${{ env.MONTH }}"
          git push

      - name: Upload Scenario as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monthly-Scenario-${{ env.YEAR }}-${{ env.MONTH }}
          path: ${{ env.OUTPUT_FILE }}
