name: Monthly Scenario Creation

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Year for the scenario (YYYY)'
        required: false
        default: ''
      month:
        description: 'Month for the scenario (MM)'
        required: false
        default: ''
  schedule:
    - cron: "0 3 1 * *" # Runs monthly on the 1st at 3:00 AM UTC

jobs:
  create-scenario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Year and Month
        id: determine_date
        run: |
          YEAR=${{ github.event.inputs.year }}
          MONTH=${{ github.event.inputs.month }}

          if [ -z "$YEAR" ] || [ -z "$MONTH" ]; then
            LAST_MONTH_DATE=$(date -d "last month" "+%Y-%m")
            YEAR=${YEAR:-${LAST_MONTH_DATE%-*}}
            MONTH=${MONTH:-${LAST_MONTH_DATE#*-}}
          fi

          echo "YEAR=$YEAR" >> $GITHUB_ENV
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "Determined year and month: $YEAR-$MONTH"

      - name: Set Input and Output Paths
        run: |
          INPUT_FILE="monthly-summaries/${{ env.YEAR }}-${{ env.MONTH }}-summary.txt"
          OUTPUT_FILE="monthly-scenario/${{ env.YEAR }}-${{ env.MONTH }}-scenario.txt"
          echo "INPUT_FILE=$INPUT_FILE" >> $GITHUB_ENV
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      - name: Check for Monthly Summary
        run: |
          if [ ! -f "$INPUT_FILE" ]; then
            echo "Error: Monthly summary file $INPUT_FILE does not exist."
            exit 1
          fi

      - name: Generate Scenario Using OpenAI API
        id: generate_scenario
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          SUMMARY=$(cat "$INPUT_FILE")

          # Debug: Log the summary
          echo "Summary Content:"
          echo "$SUMMARY"

          PAYLOAD=$(jq -n --arg summary "$SUMMARY" '{
            model: "gpt-4",
            messages: [
              {
                role: "system",
                content: "You are a language tutor helping someone practice vocabulary and sentence structures. Create a realistic dialogue scenario based on the given monthly summary."
              },
              {
                role: "user",
                content: $summary
              }
            ],
            max_tokens: 2000
          }')

          # Debug: Log the payload
          echo "Payload to OpenAI API:"
          echo "$PAYLOAD"

          RESPONSE=$(echo "$PAYLOAD" | curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @-)

          # Debug: Log the raw response
          echo "API Response:"
          echo "$RESPONSE"

          SCENARIO=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: Unable to process scenario."')

          if [[ "$SCENARIO" == Error* ]]; then
            echo "Error during scenario generation: $SCENARIO"
            exit 1
          fi

          echo -e "$SCENARIO" > "$OUTPUT_FILE"

      - name: Commit and Push Scenario to Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          mkdir -p $(dirname "$OUTPUT_FILE")
          git add "$OUTPUT_FILE"
          git commit -m "Add monthly scenario for ${{ env.YEAR }}-${{ env.MONTH }}"
          git push

      - name: Upload Scenario as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monthly-Scenario-${{ env.YEAR }}-${{ env.MONTH }}
          path: ${{ env.OUTPUT_FILE }}
