name: Monthly Summary Generator

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year to process (e.g., 2024)"
        required: false
        default: ""
      month:
        description: "Month to process (1-12)"
        required: false
        default: ""
  schedule:
    - cron: "0 8 1 * *" # Runs on the 1st of every month at 8 AM UTC

jobs:
  generate-monthly-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Year and Month
        id: set-date
        run: |
          if [ -z "${{ github.event.inputs.year }}" ]; then
            YEAR=$(date -d 'last month' '+%Y')
          else
            YEAR="${{ github.event.inputs.year }}"
          fi

          if [ -z "${{ github.event.inputs.month }}" ]; then
            MONTH=$(date -d 'last month' '+%m')
          else
            MONTH=$(printf "%02d" "${{ github.event.inputs.month }}")
          fi

          echo "YEAR=$YEAR" >> $GITHUB_ENV
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "Using year: $YEAR and month: $MONTH"

      - name: Collect Summaries
        run: |
          mkdir -p temp_summaries
          mkdir -p monthly-summaries

          # Find processed files for the specified month and combine them
          find processed/ -type f -name "${{ env.YEAR }}-${{ env.MONTH }}-*.txt" \
            | sort -r \
            | xargs cat > temp_combined_summaries.txt

          if [ ! -s temp_combined_summaries.txt ]; then
            echo "Error: No processed summaries found for ${{ env.YEAR }}-${{ env.MONTH }}."
            exit 1
          fi

      - name: Generate Vocabulary Summary
        run: |
          # Extract vocabulary from the processed files
          VOCAB_SUMMARY=$(grep -h "Vocabulary List:" processed/${{ env.YEAR }}-${{ env.MONTH }}-*.txt \
            | sed -n '/Vocabulary List:/,/^$/p' \
            | sort \
            | uniq -c \
            | sort -rn)
          echo "$VOCAB_SUMMARY" > vocab_summary.txt

      - name: Create Monthly Summaries Directory
        run: mkdir -p monthly-summaries

      - name: Generate Monthly Summary
        run: |
          OUTPUT_FILE="monthly-summaries/${{ env.YEAR }}-${{ env.MONTH }}-summary.txt"
          echo "$VOCAB_SUMMARY" > "$OUTPUT_FILE"
          echo "" >> "$OUTPUT_FILE"
          cat temp_combined_summaries.txt >> "$OUTPUT_FILE"
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      - name: Upload Monthly Summary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monthly-Summary-${{ env.YEAR }}-${{ env.MONTH }}
          path: ${{ env.OUTPUT_FILE }}
