name: Process Daily Summary

on:
  push:
    paths:
      - 'daily-summaries/**/*.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-summary:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure required directories
        run: |
          mkdir -p daily-summaries
          mkdir -p processed

      - name: Get today's summary file
        id: find_file
        run: |
          PST_DATE=$(date -d '-8 hours' '+%Y-%m-%d')
          INPUT_FILE=$(find daily-summaries/ -type f -name "$PST_DATE.txt" || true)
          if [ -z "$INPUT_FILE" ]; then
            echo "Error: No input file found for date $PST_DATE."
            exit 1
          fi
          echo "INPUT_FILE=$INPUT_FILE" >> $GITHUB_ENV

      - name: Process with OpenAI GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INPUT_FILE: ${{ env.INPUT_FILE }}
        run: |
          OUTPUT_FILE="processed/$(basename $INPUT_FILE)"
          CONTENT=$(cat $INPUT_FILE)

          ESCAPED_PROMPT=$(cat <<EOF
          Translate the following text to JLPT N5 level Japanese. Please provide the following details:

          1. Translation: The text translated into Japanese with appropriate kanji, hiragana, and grammar.
          2. Romaji: The romanized pronunciation of the translated Japanese text.
          3. Sentence Breakdown:
             - Break down each sentence and explain its key components:
               - Particles: Identify and explain the function of any particles used.
               - Verbs: Specify the verb, its dictionary form, and its conjugation.
               - Adjectives: Identify adjectives and their type (e.g., i-adjective, na-adjective).
             - Provide a brief explanation of the grammar used in the sentence.
          4. Vocabulary List: List the key words used in the translation along with their meanings, part of speech (noun, verb, adjective, etc.), and usage examples.

          Here is the text:
          $CONTENT
          EOF
          )

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "'"$ESCAPED_PROMPT"'"}],
              "max_tokens": 1000
            }')

          echo "API Response: $RESPONSE"
          TRANSLATION=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: Unable to get translation due to API issues"')
          echo "$TRANSLATION" > $OUTPUT_FILE
          echo "Translation saved to $OUTPUT_FILE"

      - name: Commit processed output
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add processed/
          git commit -m "Processed summary for $(date -d '-8 hours' '+%
