name: Daily Process Summary

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to process (YYYY-MM-DD, optional)'
        required: false
        default: ''
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8 AM UTC

jobs:
  process-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Directories
        run: |
          mkdir -p daily-summaries
          mkdir -p processed

      - name: Determine Date
        id: determine_date
        run: |
          if [ -z "${{ github.event.inputs.date }}" ]; then
            PST_DATE=$(date -d '-1 day -8 hours' '+%Y-%m-%d')
          else
            PST_DATE=${{ github.event.inputs.date }}
          fi
          echo "PST_DATE=$PST_DATE" >> $GITHUB_ENV
          echo "Processing date: $PST_DATE"

      - name: Find Input File
        id: find_file
        run: |
          INPUT_FILE="daily-summaries/${PST_DATE}.txt"
          if [ ! -f "$INPUT_FILE" ]; then
            echo "Error: No input file found for date $PST_DATE."
            exit 1
          fi
          echo "INPUT_FILE=$INPUT_FILE" >> $GITHUB_ENV
          echo "Input file found: $INPUT_FILE"

      - name: Process File with OpenAI API
        id: process_file
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          INPUT_FILE="${{ env.INPUT_FILE }}"
          OUTPUT_FILE="processed/$(basename "$INPUT_FILE")"
          CONTENT=$(cat "$INPUT_FILE")

          if [ -z "$CONTENT" ]; then
            echo "Error: Input file is empty or unreadable."
            exit 1
          fi

          echo "Sending content to OpenAI API for processing..."

          ESCAPED_PROMPT=$(jq -n --arg text "$CONTENT" '{
            model: "gpt-3.5-turbo",
            messages: [
              {
                role: "user",
                content: (
                  "Translate the following text to JLPT N5 level Japanese and provide detailed annotations in a clean, structured format. The output should include:\n\n" +
                  "1. **Translation**: Provide the text translated into Japanese with appropriate kanji, hiragana, and grammar, written as complete sentences with correct punctuation.\n\n" +
                  "2. **Romaji**: Provide the romanized pronunciation of the translated Japanese text, corresponding to the Japanese sentences.\n\n" +
                  "3. **Sentence Breakdown**:\n" +
                  "   - Break down each Japanese sentence into key components, explaining:\n" +
                  "     - Particles: Identify and explain their function.\n" +
                  "     - Verbs: Specify the verb, its dictionary form, and its conjugation.\n" +
                  "     - Adjectives: Identify their type (e.g., i-adjective, na-adjective).\n" +
                  "   - Provide a brief explanation of the grammar used.\n\n" +
                  "4. **Vocabulary List**: List the key words used in the translation, with:\n" +
                  "   - Their meanings.\n" +
                  "   - Part of speech (e.g., noun, verb, adjective).\n" +
                  "   - Example sentences, if applicable.\n\n" +
                  "5. **Original English Text**: Include the original English sentences as a footer, clearly marked as \"Original English Text.\"\n\n" +
                  "Ensure the output is well-formatted and easy to read, without any unnecessary escape sequences or line breaks. Use the following text:\n" +
                  $text
                )
              }
            ],
            max_tokens: 2000
          }')

          RESPONSE=$(echo "$ESCAPED_PROMPT" | curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @-)

          if [ -z "$RESPONSE" ]; then
            echo "Error: No response from OpenAI API."
            exit 1
          fi

          TRANSLATION=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: Unable to get translation due to API issues"')

          if [[ "$TRANSLATION" == Error* ]]; then
            echo "Error during translation: $TRANSLATION"
            exit 1
          fi

          echo "Writing translation to: $OUTPUT_FILE"
          echo "$TRANSLATION" > "$OUTPUT_FILE"

          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV
          echo "Processing complete. Translation saved to $OUTPUT_FILE"

      - name: Commit Processed File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add processed/*
          git commit -m "Add processed file for ${{ env.PST_DATE }}"
          git push
