name: Process Daily Summary

on:
  push:
    paths:
      - 'daily-summaries/**/*.txt'  # Trigger on changes to .txt files in daily-summaries
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-summary:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure directories exist
      - name: Ensure required directories
        run: |
          echo "Checking required directories..."
          mkdir -p daily-summaries
          mkdir -p processed
          echo "Directories ensured."

      # Step 3: Debug - List files in daily summaries folder
      - name: Debug - List daily summaries folder
        run: |
          echo "Listing files in daily-summaries folder:"
          ls -l daily-summaries || echo "No files found in daily-summaries"

      # Step 4: Adjust for PST time zone and find today's summary file
      - name: Get today's summary file
        id: find_file
        run: |
          # Adjust for PST (UTC-8)
          PST_DATE=$(date -d '-8 hours' '+%Y-%m-%d')

          # Check for a pushed file first
          INPUT_FILE=$(git diff --name-only HEAD | grep '^daily-summaries/.*\.txt' || true)

          # If no pushed file, look for today's file in the committed files
          if [ -z "$INPUT_FILE" ]; then
            echo "No pushed file detected. Looking for today's file for PST date ($PST_DATE)..."
            INPUT_FILE=$(find daily-summaries/ -type f -name "$PST_DATE.txt" || true)
          fi

          # Print debug info
          echo "Detected input file: $INPUT_FILE"

          # Exit if no file is found
          if [ -z "$INPUT_FILE" ]; then
            echo "Error: No input file found in the daily-summaries folder for today (PST date: $PST_DATE)."
            exit 1
          fi

          echo "::set-output name=file::$INPUT_FILE"

      # Step 5: Process with OpenAI GPT
      - name: Process with OpenAI GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          INPUT_FILE="${{ steps.find_file.outputs.file }}"
          OUTPUT_FILE="processed/$(basename $INPUT_FILE)"
          CONTENT=$(cat $INPUT_FILE)

          PROMPT="Translate the following text to JLPT N5 level Japanese, including hiragana, kanji, and a vocabulary breakdown:\n\n$CONTENT"

          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "'"$PROMPT"'"}],
              "max_tokens": 1000
            }')

          TRANSLATION=$(echo $RESPONSE | jq -r '.choices[0].message.content')

          echo "$TRANSLATION" > $OUTPUT_FILE

      # Step 6: Commit the processed file
      - name: Commit processed output
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add processed/
          git commit -m "Processed summary for $(date -d '-8 hours' '+%Y-%m-%d')"
          git push
