name: Process Daily Summary

on:
  push:
    paths:
      - 'daily-summaries/**/*.txt'  # Trigger on changes to .txt files in daily-summaries
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grants write access to push changes back to the repository

jobs:
  process-summary:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure required directories
      - name: Ensure required directories
        run: |
          mkdir -p daily-summaries
          mkdir -p processed

      # Step 3: Find today's file
      - name: Get today's summary file
        id: find_file
        run: |
          PST_DATE=$(date -d '-8 hours' '+%Y-%m-%d')
          INPUT_FILE=$(find daily-summaries/ -type f -name 
