name: Process Daily Summary

on:
  push:
    paths:
      - 'daily-summaries/**/*.txt'  # Trigger on changes to any .txt file in daily-summaries

jobs:
  process-summary:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Process with OpenAI GPT
      - name: Process with OpenAI GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Get today's file based on the push event
          INPUT_FILE=$(git diff --name-only HEAD~1 | grep '^daily-summaries/.*\.txt')
          OUTPUT_FILE="processed/$(basename $INPUT_FILE)"

          # Read input content
          CONTENT=$(cat $INPUT_FILE)

          # Define the OpenAI prompt
          PROMPT="Translate the following text to JLPT N5 level Japanese, including hiragana, kanji, and a vocabulary breakdown:\n\n$CONTENT"

          # Call OpenAI API
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "'"$PROMPT"'"}],
              "max_tokens": 1000
            }')

          # Extract the translation content
          TRANSLATION=$(echo $RESPONSE | jq -r '.choices[0].message.content')

          # Save the output to the processed folder
          echo "$TRANSLATION" > $OUTPUT_FILE

      # Step 3: Commit the processed file
      - name: Commit processed output
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add processed/
          git commit -m "Processed summary for $(date +'%Y-%m-%d')"
          git push
