name: Process Daily Summary

on:
  push:
    paths:
      - 'daily-summaries/**/*.txt'  # Trigger on changes to .txt files in daily-summaries

jobs:
  process-summary:
    runs-on: ubuntu-22.04  # Explicit version to avoid deprecation warnings

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug - List files in the daily summaries folder
      - name: Debug - List daily summaries folder
        run: |
          echo "Listing files in the daily-summaries folder:"
          ls -l daily-summaries || echo "No files found in daily-summaries"

      # Step 3: Get today's file based on the push event
      - name: Get today's file based on the push event
        id: find_file
        run: |
          # Check if there's a previous commit
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            echo "Previous commit found. Checking for modified files..."
            INPUT_FILE=$(git diff --name-only HEAD~1 | grep '^daily-summaries/.*\.txt' || true)
          else
            echo "No previous commit. Checking for untracked files..."
            INPUT_FILE=$(git ls-files --others --exclude-standard | grep '^daily-summaries/.*\.txt' || true)
          fi

          # Print debug info
          echo "Found input file: $INPUT_FILE"

          # Exit if no file is found
          if [ -z "$INPUT_FILE" ]; then
            echo "Error: No input file found in the daily-summaries folder."
            exit 1
          fi

          echo "::set-output name=file::$INPUT_FILE"

      # Step 4: Process with OpenAI GPT
      - name: Process with OpenAI GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
       
