name: Process Daily Summary

on:
  push:
    paths:
      - 'daily-summaries/**/*.txt'  # Trigger on changes to .txt files in daily-summaries
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grants write access to push changes back to the repository

jobs:
  process-summary:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure required directories
      - name: Ensure required directories
        run: |
          mkdir -p daily-summaries
          mkdir -p processed

      # Step 3: Find today's file
      - name: Get today's summary file
        id: find_file
        run: |
          PST_DATE=$(date -d '-8 hours' '+%Y-%m-%d')
          INPUT_FILE=$(find daily-summaries/ -type f -name "$PST_DATE.txt" || true)
          if [ -z "$INPUT_FILE" ]; then
            echo "Error: No input file found for date $PST_DATE."
            exit 1
          fi
          echo "INPUT_FILE=$INPUT_FILE" >> $GITHUB_ENV

      # Step 4: Process with OpenAI GPT
      - name: Process with OpenAI GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INPUT_FILE: ${{ env.INPUT_FILE }}
        run: |
          OUTPUT_FILE="processed/$(basename $INPUT_FILE)"
          CONTENT=$(cat $INPUT_FILE)

          ESCAPED_PROMPT=$(echo "Translate the following text to JLPT N5 level Japanese:\n\n$CONTENT" | jq -Rs .)

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": '"$ESCAPED_PROMPT"'}],
              "max_tokens": 1000
            }')

          TRANSLATION=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "Error: Unable to get translation due to API issues"')
          echo "$TRANSLATION" > $OUTPUT_FILE
          echo "File updated: $OUTPUT_FILE"

      # Step 5: Add a timestamp to ensure changes are detected
      - name: Add timestamp to processed file
        run: |
          OUTPUT_FILE="processed/$(basename ${{ env.INPUT_FILE }})"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "\n\nProcessed on: $TIMESTAMP" >> $OUTPUT_FILE
          echo "Added timestamp to $OUTPUT_FILE"

      # Step 6: Commit processed file
      - name: Commit processed output
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add processed/
          
          # Force commit changes if they exist
          git commit -m "Processed summary for $(date -d '-8 hours' '+%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "No changes to push"
