name: Send Processed Email

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date for which the email will be sent (optional, format YYYY-MM-DD)"
        required: false
        default: ""
  schedule:
    - cron: "0 10 * * *" # Runs daily at 10 AM UTC

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Date
        id: determine_date
        run: |
          if [ -z "${{ github.event.inputs.date }}" ]; then
            DATE=$(date -d '-1 day -8 hours' '+%Y-%m-%d')
          else
            DATE="${{ github.event.inputs.date }}"
          fi
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "Using date: $DATE"

      - name: Verify Processed File
        id: verify_file
        run: |
          PROCESSED_FILE="processed/${DATE}.txt"
          if [ ! -f "$PROCESSED_FILE" ]; then
            echo "Error: Processed file $PROCESSED_FILE does not exist."
            exit 1
          fi

          echo "PROCESSED_FILE=$PROCESSED_FILE" >> $GITHUB_ENV
          echo "Processed file found: $PROCESSED_FILE"

      - name: Read File Content Safely
        id: read_file
        run: |
          PROCESSED_FILE="processed/${DATE}.txt"
          TRANSLATION_CONTENT=$(cat "$PROCESSED_FILE")
          # Save to a temporary file for multiline-safe usage
          echo "$TRANSLATION_CONTENT" > translation_content.txt
          echo "Saved translation content to translation_content.txt"

      - name: Send Processed File via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Processed Summary for ${{ env.DATE }}"
          body: |
            Hello,

            The processed summary for ${{ env.DATE }} is as follows:

            $(cat translation_content.txt)

            Best regards,
            GitHub Actions
          to: seanthomasward@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: ${{ env.PROCESSED_FILE }}
