name: Send Processed Email

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date for which the email will be sent (optional, format YYYY-MM-DD)"
        required: false
        default: ""
  schedule:
    - cron: "0 10 * * *" # Runs daily at 10 AM UTC

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Date
        id: determine_date
        run: |
          if [ -z "${{ github.event.inputs.date }}" ]; then
            DATE=$(date -d '-1 day -8 hours' '+%Y-%m-%d')
          else
            DATE="${{ github.event.inputs.date }}"
          fi
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "Using date: $DATE"

      - name: Verify Processed File
        id: verify_file
        run: |
          PROCESSED_FILE="processed/${DATE}.txt"
          if [ ! -f "$PROCESSED_FILE" ]; then
            echo "Error: Processed file $PROCESSED_FILE does not exist."
            exit 1
          fi

          TRANSLATION_CONTENT=$(cat "$PROCESSED_FILE")
          ENCODED_TRANSLATION=$(echo "$TRANSLATION_CONTENT" | base64)
          
          # Save encoded content and file path to the environment
          echo "TRANSLATION_CONTENT=$ENCODED_TRANSLATION" >> $GITHUB_ENV
          echo "PROCESSED_FILE=$PROCESSED_FILE" >> $GITHUB_ENV
          echo "Processed file found: $PROCESSED_FILE"

      - name: Send Processed File via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Processed Summary for ${{ env.DATE }}"
          body: |
            Hello,

            The processed summary for {{ env.DATE }} is as follows:

            $(echo ${{ env.TRANSLATION_CONTENT }} | base64 --decode)

            Best regards,
            GitHub Actions
          to: seanthomasward@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: ${{ env.PROCESSED_FILE }}
