name: Send Monthly Summary Email

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year for the monthly summary (optional, format YYYY)"
        required: false
        default: ""
      month:
        description: "Month for the monthly summary (optional, format MM)"
        required: false
        default: ""
  schedule:
    - cron: "0 10 2 * *" # Runs monthly on the 2nd at 10 AM UTC

jobs:
  send-monthly-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Year and Month
        id: determine_date
        run: |
          YEAR=${{ github.event.inputs.year }}
          MONTH=${{ github.event.inputs.month }}

          if [ -z "$YEAR" ] || [ -z "$MONTH" ]; then
            LAST_MONTH_DATE=$(date -d "last month" "+%Y-%m")
            YEAR=${YEAR:-${LAST_MONTH_DATE%-*}}
            MONTH=${MONTH:-${LAST_MONTH_DATE#*-}}
          fi

          echo "YEAR=$YEAR" >> $GITHUB_ENV
          echo "MONTH=$MONTH" >> $GITHUB_ENV
          echo "Using year and month: $YEAR-$MONTH"

      - name: Verify Monthly Summary File
        id: verify_file
        run: |
          SUMMARY_FILE="monthly-summaries/${YEAR}-${MONTH}-summary.txt"
          if [ ! -f "$SUMMARY_FILE" ]; then
            echo "Error: Monthly summary file $SUMMARY_FILE does not exist."
            exit 1
          fi

          echo "SUMMARY_FILE=$SUMMARY_FILE" >> $GITHUB_ENV
          echo "Monthly summary file found: $SUMMARY_FILE"

      - name: Read Monthly Summary File Content
        id: read_file
        run: |
          SUMMARY_FILE="monthly-summaries/${YEAR}-${MONTH}-summary.txt"
          SUMMARY_CONTENT=$(cat "$SUMMARY_FILE")
          echo "$SUMMARY_CONTENT"
          echo "SUMMARY_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$SUMMARY_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Monthly Summary Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Monthly Summary for ${{ env.YEAR }}-${{ env.MONTH }}"
          body: |
            Hello,

            The monthly summary for ${{ env.YEAR }}-${{ env.MONTH }} is as follows:

            ${{ env.SUMMARY_CONTENT }}

            Best regards,
            GitHub Actions
          to: seanthomasward@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: monthly-summaries/${{ env.YEAR }}-${{ env.MONTH }}-summary.txt
