name: Send Email Summary

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      date:
        description: 'Date of the summary to send (YYYY-MM-DD)'
        required: false
        default: ''
  
  # Automatic Trigger from "Daily Process Summary"
  workflow_run:
    workflows: ["Daily Process Summary"] # Ensure this matches the name of your translation workflow
    types:
      - completed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Date
        id: determine_date
        run: |
          if [ -z "${{ github.event.inputs.date }}" ]; then
            DATE=$(date -d '-1 day -8 hours' '+%Y-%m-%d')
          else
            DATE=${{ github.event.inputs.date }}
          fi
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "Using date: $DATE"

      - name: Check Processed File
        id: check_file
        run: |
          PROCESSED_FILE="processed/${DATE}.txt"

          if [ ! -f "$PROCESSED_FILE" ]; then
            echo "Error: Processed file $PROCESSED_FILE does not exist."
            exit 1
          fi

          TRANSLATION_CONTENT=$(cat "$PROCESSED_FILE")
          echo "TRANSLATION_CONTENT=$TRANSLATION_CONTENT" >> $GITHUB_ENV
          echo "Processed file found: $PROCESSED_FILE"

      - name: Send Processed File via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Processed Summary for ${{ env.DATE }}"
          body: |
            Hello,

            The processed summary for {{ env.DATE }} is as follows:

            ${{ env.TRANSLATION_CONTENT }}

            Best regards,
            GitHub Actions
          to: seanthomasward@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          attachments: processed/${{ env.DATE }}.txt
